---
title: "median household income"
author: "Brianna Carnagie"
date: "2023-10-18"
output: html_document
---


To create the second map, use Census Data Explorer or Tidycensus package to get county-level median household income for Pennsylvania for 2020. Use Natural breaks Jenks to classify the data with four classes, and an appropriate color scheme.


```{r setup, include=FALSE}
library(tidycensus)
library(sf)
library(ggplot2)
```

```{r}


# Three steps to minimize errors

# Step 1: install the packages (need to install only once)
install.packages("tidycensus")   # access US census data
install.packages("tidyverse")    # data management/visualization (several packages)
install.packages("sf")           # GIS package
install.packages("tmap")         # mapping package
install.packages("tmaptools")    # additional tools for tmap 
install.packages("shinyjs")


# Step 2: load packages 
library(tidycensus)
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)


### Get census data from tidycensus 

# Set API key
census_api_key("25ac4cfc87037082641d4f897715ea64a893615d", install=TRUE)

readRenviron("~/.Renviron")

 # Get a list of all variables available from census
census_data <- load_variables(year = 2020, 
                              dataset = "acs5", 
                              cache = TRUE)

View(census_data) # gives us the names of the variables

```


```{r}
# Define your query
PA_income2 <- get_acs(geography = "county", variables = "B19013_001", state = "PA", geometry = TRUE)


# Assign final map to an object 
tm_shape(PA_income2) +   
  tm_polygons(col = "estimate",
              style = "quantile",
              n = 4,
              palette = "Greens",
              border.col = "black",
              title = "Median Income") + 
  tm_legend(legend.position = c(0.95, .37))+
  tm_layout(title = "Median Income in Pennsylvania, 2020",  
            title.size = 2.5,                                                      
            title.position = c(.25, .93),                                         
            inner.margins = c(0.10, 0.10, 0.1, 0.01),                            
            frame = FALSE,                                                       
            legend.title.size = .9) +        
  tm_compass(type="arrow",                             
             position=c(.85, 0.02),                     
             size = 1.2) +                             
  tm_scale_bar(position=c(.55, 0.01),                   
               size = 0.6) +
  tm_credits("Author: Brianna Carnagie \nSource: fractracker.org \nOctober 18, 2023",
             size = .7,
             position = c(.024,.01)) +                             
  tm_text(text  = "county", size = "AREA") -> final_map             


# Save map in wd jpg/tiff/pgn

tmap_save(final_map, 
          dpi = 300,
          width = 6,
          height = 10,
          filename = "insured_nj.png")

# Save sf dataframe as shapefile
st_write(nj_insured,"NJ_insured_r.shp")


append=FALSE




```

